networks:
  app-tier:
    driver: bridge

services:
  yapp-blue:
    container_name: yapp-blue
    networks:
      - app-tier
    image: yapp26th/fitrun-dev:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    pull_policy: always
    healthcheck:
      test: "curl -f http://localhost:8080/check/health || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs

  yapp-green:
    container_name: yapp-green
    networks:
      - app-tier
    image: yapp26th/fitrun-dev:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    pull_policy: always
    healthcheck:
      test: "curl -f http://localhost:8080/check/health || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs

  nginx:
    depends_on:
      - yapp-green
      - yapp-blue
    image: nginx:1.15-alpine
    container_name: nginx
    networks:
      - app-tier
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/log:/var/log/nginx
      - /etc/localtime:/etc/localtime
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs:/var/log/fitrun
      - ./promtail/promtail-config.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml -log.level=debug
    restart: unless-stopped
    networks:
      - app-tier
