spring:
  config:
    import: dev-env.yml

  datasource:
    url: jdbc:mysql://${secret.database.host}:${secret.database.port}/${secret.database.name}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${secret.database.user}
    password: ${secret.database.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    static-path-pattern: /static/**

management:
  server:
    port: ${secret.management.port}

  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: ${secret.management.path}
    jmx:
      exposure:
        exclude: "*"
    access:
      default: none

  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-components: never
