spring:
  datasource:
    url: jdbc:h2:mem:yapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      client-name: fitrun
      host: localhost
      port: 6739

jwt:
  issuer: test
  access-secret: 3x+mpl3+S3cr3t+K3y+W1th+M0r3+Ch+r+ct3rs+For+Access!
  access-expiration-millis: 3600000
  refresh-secret: 4n0th3r+S3cur3+K3y+That+Is+L0ng+En0ugh+F0r+Refresh!
  refresh-expiration-millis: 3600000

oidc:
  apple:
    api:
      url: https://appleid.apple.com
      clientId: test-client-id
  kakao:
    api:
      url: https://kauth.kakao.com
      clientId: test-client-id

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
