spring:
  config:
    import: staging-env.yml
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 3

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        leak-detection-threshold: 5000
