spring:
  config:
    import: staging-env.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        leak-detection-threshold: 5000
