spring:
  config:
    import: dev-env.yml

  datasource:
    url: jdbc:mysql://${secret.database.host}:${secret.database.port}/${secret.database.name}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${secret.database.user}
    password: ${secret.database.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: info
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: ${secret.logging.file.name}
  logback:
    rollingpolicy:
      file-name-pattern: ${secret.logging.file.pattern}
      max-history: 30

management:
  server:
    port: ${secret.management.port}

  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: ${secret.management.path}
    jmx:
      exposure:
        exclude: "*"
    access:
      default: none

  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-components: never
      access: unrestricted
