spring:
  config:
    import: dev-env.yml
  datasource:
    url: jdbc:h2:mem:yapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      client-name: fitrun
      host: localhost
      port: 6379
  cloud:
    gcp:
      project-id: ${secret.gcp.project-id}
      credentials:
        location: ${secret.gcp.location}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  issuer: http://test.com
  access-secret: Z1RqM2ZQamRia0hoV01UdVgwYWQ5V0RYdVZlTzdlSFk=
  access-expiration-millis: 3600000
  refresh-secret: a2JqeG1IemZYZVRIYlpqM2hHN2xLVGFxVDR0b0RHc2s=
  refresh-expiration-millis: 604800000

gcp:
  bucket: ${secret.gcp.bucket-name}

oidc:
  response-millis: 3600000
  apple:
    api:
      url: https://appleid.apple.com
      client-id:
        - test-app-key-apple
        - test-rest-key-apple
  kakao:
    api:
      url: https://kauth.kakao.com
      client-id:
        - test-app-key-kakao
        - test-rest-key-kakao
