spring:
  config:
    import: staging-env.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  access-expiration-millis: 31536000000
  refresh-expiration-millis: 31536000000
