spring:
  config:
    import: staging-env.yml
  datasource:
    hikari:
      maximum-pool-size: 70
      minimum-idle: 3
      idle-timeout: 30000
      connection-timeout:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        leak-detection-threshold: 5000
