server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{LOKI_HOST}/loki/api/v1/push

scrape_configs:
  - job_name: fitrun-app
    static_configs:
      - targets: ["localhost"]
        labels:
          job: fitrun-app
          __path__: /var/log/fitrun/app/*.log
