name: push-container
author: choiwonjun
description: push-container
inputs:
  profile:
    description: "작업 프로필"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker Image
      shell: bash
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fitrun-${{inputs.container-name}}:latest .

    - name: Push Docker Image
      shell: bash
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fitrun-${{inputs.container-name}}:latest
