name: DEV CD

on:
  workflow_dispatch:
  pull_request: # TODO
    branches: [ dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.REPO_TOKEN }}

      - name: Debug - List submodule folder contents
        run: |
          ls -Rla ./Yapp-26th-env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fitrun-dev:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fitrun-dev:latest

      - name: Copy deployment files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_BASTION_IP }}
          username: ${{ secrets.DEV_BASTION_USERNAME }}
          key: ${{ secrets.DEV_BASTION_KEY }}
          port: 22
          timeout: 120s
          source: "deployment/dev/"
          target: /home/yapp

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_BASTION_IP }}
          username: ${{ secrets.DEV_BASTION_USERNAME }}
          key: ${{ secrets.DEV_BASTION_KEY }}
          port: 22
          script: |
            rm -rf ~/data
            mv ~/deployment/dev/* ~/
            rm -rf ~/deployment
            bash ./deploy.sh
