name: Dev CI

on:
  pull_request:
    branches : [ dev ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/start-redis-container

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.REPO_TOKEN }}

      - name: Run tests
        run: ./gradlew clean test
